name: meta-clr
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.7
  - argon2-cffi=20.1.0
  - attrs=20.3.0
  - av=8.0.3
  - backcall=0.2.0
  - bleach=3.3.0
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - dataclasses=0.8
  - decorator=4.4.2
  - defusedxml=0.7.1
  - distro=1.5.0
  - entrypoints=0.3
  - idna=2.10
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.3
  - importlib-metadata=3.7.3
  - ipykernel=5.5.0
  - ipython=7.16.1
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - Jinja2=2.11.3
  - jsonschema=3.2.0
  - MarkupSafe=1.1.1
  - mistune=0.8.4
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.5.1
  - opencv
  - packaging=20.9
  - pandas=1.1.5
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - Pillow=8.1.2
  - proglog=0.1.9
  - prompt-toolkit=3.0.18
  - ptyprocess=0.7.0
  - pycparser=2.20
  - Pygments=2.8.1
  - pyparsing=2.4.7
  - pyrsistent=0.17.3
  - python-dateutil=2.8.1
  - pytorch
  - pytz=2021.1
  - pyzmq=22.0.3
  - qtconsole=5.0.3
  - QtPy=1.9.0
  - requests=2.25.1
  - Send2Trash=1.5.0
  - six=1.15.0
  - terminado=0.9.3
  - testpath=0.4.4
  - torchaudio
  - torchvision=0.9.0
  - tornado=6.1
  - tqdm=4.59.0
  - traitlets=4.3.3
  - typing-extensions=3.7.4.3
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - widgetsnbextension=3.5.1
  - zipp=3.4.1
